'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class endereco
    Public Property id_pessoa As Integer
    Public Property cep As Nullable(Of Decimal)
    Public Property logradouro As String
    Public Property numero As Nullable(Of Decimal)
    Public Property bairro As String
    Public Property municipio As String
    Public Property uf As String

    Public Overridable Property pessoa As pessoa

End Class
