'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class telefone
    Public Property id_telefone As Integer
    Public Property tipo As String
    Public Property numero As Decimal
    Public Property id_pessoa As Integer

    Public Overridable Property pessoa As pessoa

End Class
