USE [master]
GO

/****** Object:  Database [Cadastro]    Script Date: 08/08/2018 04:45:04 ******/
DROP DATABASE [Cadastro]
GO

/****** Object:  Database [Cadastro]    Script Date: 08/08/2018 04:45:04 ******/
CREATE DATABASE [Cadastro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cadastro', FILENAME = N'C:\Users\Usuario\Cadastro.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cadastro_log', FILENAME = N'C:\Users\Usuario\Cadastro_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Cadastro] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cadastro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cadastro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cadastro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cadastro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cadastro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cadastro] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cadastro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cadastro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cadastro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cadastro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cadastro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cadastro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cadastro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cadastro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cadastro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cadastro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cadastro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cadastro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cadastro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cadastro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cadastro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cadastro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cadastro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cadastro] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cadastro] SET  MULTI_USER 
GO

ALTER DATABASE [Cadastro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cadastro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cadastro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cadastro] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Cadastro] SET  READ_WRITE 
GO

